spring:
  application:
    name: service-gateway
  cloud:
    zookeeper:
      connect-string: 192.168.200.152:2181
    gateway:
      discovery:
        locator:
          enabled: true  #是否可以通过其他服务的serviceId来转发到具体的服务实例。默认为false
          lower-case-service-id: true  #该配置开启后，服务名可以小写，微服务应用名默认大写访问
      routes:
        - id: service-oauth2  #oauth2服务
          uri: lb://service-oauth2
          predicates:
            - Path=/auth/**   #如果请求地址满足/auth/**,则转发到auth服务
          filters:
            - StripPrefix=1   #去除请求地址中的auth
        - id: service-order   #订单服务
          uri: lb://service-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: service-goods   #商品服务
          uri: lb://service-goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1

server:
  port: 8081